services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=inception
      - MONGO_INITDB_ROOT_PASSWORD=in!ce1p#2tion
    ports:
      - 27017:27017
    volumes:
      - /data/mongo-data:/data/db

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - /data/qdrant-data:/qdrant/storage
